config/routes.rb
Rails.application.routes.draw do
  resources :inventories, only: [:index, :new, :create, :destroy, :edit] do
    resources :products, only: [:index, :new, :create, :destroy, :show]
  end
  
  root to: 'inventories#index'

  resource :session , only: [:new, :create, :destroy]
  get 'users/:id/reactivate' => 'users#reactivate', as: :reactivate_user
  get 'users/' => 'users#index', as: :users
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :user
  post 'users/' => 'users#create'
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

end

app/models/inventory.rb
class Inventory
  include Mongoid::Document
  field :user_id, type: String
  field :product_id, type: String
  field :quantity, type: Float
  field :category_name, type: String

  belongs_to :user
  has_many :products
  #has_many :categories
  #has_many :subcategories
  #has_many :makes
end

app/models/product.rb
class Product
  include Mongoid::Document
  field :product_name, type: String
  field :product_purchase_price, type: String
  field :product_estimate_price, type: String
  field :product_category_name, type: String
  field :product_make, type: String
  field :product_warranty, type: Boolean
  field :product_warranty_length, type: Float

  #belongs_to :user
  belongs_to :inventory
  # has_many :category
  # has_many :subcategory
  # has_many :make
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  field :first_name, type: String
  field :last_name, type: String
  field :password_digest, type: String
  field :address, type: String
  field :city, type: String
  field :state, type: String
  field :postal_code, type: String
  field :email_address, type: String
  field :is_active, type: Mongoid::Boolean, default: true

  has_secure_password

  has_many :inventories
  # has_many :categories
  # has_many :subcategories
  # has_many :makes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
	# before_action :get_inventory, only: [:show, :edit, :update, :destroy]
	# before_action :check_security, only: [:show, :edit, :update, :destroy]
	
	def home
		@user = User.new
	end

	def index
		if !current_user
			redirect_to home_path
			return
		end
		#@inventories = Inventory.all
		@inventories = current_user.inventories
	end

	# def show
	# 	@inventories = current_user.inventories
	# 	@inventory = Inventory.find(params:[:id])
	# end

	def new
		if !current_user
			redirect_to new_sessions_path			
		return
		end
		@inventory = Inventory.new
	end

	def create
		if !current_user
			redirect_to new_sessions_path
			return
		end
			inventory = current_user.inventories.new(params.require(:inventory).permit(:user_id, :product_id, :quantity, :category_name))
			if inventory.save
				redirect_to inventories_path
			end
	end

	# def edit
	# 	@inventory = Inventory.find(params[:id])
	# end

	# def update
	# 	@inventory = Inventory.find(params[:id])
	# 	if @inventory.update_attributes(params.require(:inventory).permit(:user_id, :product_id, :quantity, :category_name))
	# 		redirect_to inventories_path
	# 	else
	# 		render 'edit'
	# 	end
	# end

	def destroy
		Inventory.find(params[:id]).destroy
		redirect_to inventories_path
	end

# private
# 	def get_inventory
# 		@inventory = Inventory.find(params[:id])
# 	end

# 	def check_security
# 		# if they're not logged in or they dont ownt this inventory boot them to the home page
# 		if current_user || @inventory.user != current_user
# 			redirect_to home_path
# 		end
# 		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :get_inventory, :check_security 

	def index
		@products = @inventory.products
	end

	def show
		@product = Product.find(params:[:id])
	end

	def new
		#@inventory = Inventory.find([:inventory_id])
		@product = Product.new
	end

	def create
		product = Product.new(params.require(:product).permit(:product_name, :product_purchase_price, :product_estimate_price, :product_category_id, :product_make, :product_warranty, :product_warranty_length))
		#attach this product to inventory
		product.inventory = @inventory
		if product.save
			redirect_to inventory_products_path(@inventory.id)
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(params.require(:product).permit(:product_name, :product_purchase_price, :product_estimate_price, :product_category_id, :product_make, :product_warranty, :product_warranty_length))
			redirect_to products_path
		else
			render 'edit'
		end
	end

	def destroy
		Product.find(params[:id]).destroy
		redirect_to inventory_products_path(@inventory.id)
	end

private

	def get_inventory
		@inventory = Inventory.where(:id => params[:inventory_id]).first
	end

	def check_security
		# if they're not logged in or they dont own this inventory boot them to the home page
		if (!current_user) || (:inventory_id != current_user)
			redirect_to home_path
		end
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
		@is_login = false
	end

	def create
		#Find the user that is trying to log in
		u = User.where(email_address: params[:user][:email_address]).first
		if u && u.authenticate(params[:user][:password])
			if u.is_active == false
				redirect_to reactivate_user_path(u.id)
			end
			#Store as a cookie in the user browser as the ID of them,
			#indicating they are logged in
			session[:user_id] = u.id.to_s
			redirect_to home_path
		else
			redirect_to new_session_path
		end
	end

	def destroy
		reset_session
		redirect_to new_session_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
		@users = User.where(is_active: true)
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation, :address, :city, :state, :postal_code, :email_address))
		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def edit
		 @user = User.find(params[:id])
	end

	def update
			@user = User.find(params[:id])
			if current_user != @user
				if current_user
					redirect_to user_path(current_user)
			else 
				redirect_to new_sessions_path
			end
			elsif  @user.update_attributes(params.require(:user).permit(:first_name, :last_name, :password, :address, :city, :state, :postal_code, :email_address, :is_active))
					redirect_to users_path
			else
				render :edit
			end
		end
	def destroy
		@user = User.find(params[:id])
		@users.is_active = false
		@user.save
		# @users.destroy
		redirect_to users_path
	end

	def reactivate
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inventories/index.html.erb
<h1>Username's Merchlog</h1>

<div class="jumbotron">
	<h1><%= current_user.first_name %> Merch Stats</h1>
		<p>...</p>
		<ul>
			<li>Merch Count: <%= current_user.last_name %> </li>
			<li>Merch Estimated Worth:</li>
			<li>Most Valuable Merch:</li>
			<li>MerchAlerts:</li>
		</ul>
		<p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p>
	</div>



<!-- <div class="navigation">
	<h6>My Merch</h6>
	<ul>
		<li>Summary</li>
		<li>Manuals</li>
		<li>Warranties</li>
	</ul>

	<h6>Categories</h6>
	<ul>
		<li>Fed from category model</li>
		<li>Sub categories</li>
	</ul>
</div> -->

<div class="inventory_list">
	
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Categories</h3>
  </div>
  <div class="panel-body">
    Electronics
  </div>
  <div class="panel-body">
    TVs
  </div>
</div>


<ul>
<% @inventories.each do |p| %>
	<li>
		<%= link_to "more info", inventory_products_path(p.id) %>
	</li>
<% end %>
</ul>

app/views/inventories/new.html.erb
<h1>Make New Inventory</h1>

<%= form_for @inventory do |f| %>
	<%= f.text_field :category_name, placeholder: "What Category would this Log fit in?" %>
	<%= f.collection_select :product_id, Product.all, :id, :product_name %>
	<%= f.text_field :quantity, placeholder: "Quantity" %>
	<%= f.submit %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div> -->

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <ul class="nav navbar-nav">
	      <!-- <li class="active"><a href="#">Link</a></li> -->
	      <!-- <li><a href="#">Link</a></li> -->
	      <li class="dropdown">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Navigate <span class="caret"></span></a>
	        <ul class="dropdown-menu" role="menu">
	        	<% if current_user %>
	          <li><%= link_to "New Merch", new_inventory_path %></li>
	          <li><%= link_to "Merch Log", inventories_path %></li>
	          <li><%= link_to "Asset Summary", users_path %></li>
	          <li><%= link_to "Edit Merch Log", edit_user_path(current_user) %></li>
	          <li class="divider"></li>
	          <li><%= link_to "Home", inventories_path %></li>
	          <% else %>
	          <li class="divider"></li>
	          <%= link_to "Sign up", new_user_path if !@is_signup %>
	      		<%= link_to "Log in", new_session_path if !@is_login %>
	          <% end %>
	        </ul>
	      </li>
	    </ul>
	    <form class="navbar-form navbar-left" role="search">
	      <div class="form-group">
	        <input type="text" class="form-control" placeholder="Search">
	      </div>
	      <button type="submit" class="btn btn-default">Submit</button>
	    </form>
	    <ul class="nav navbar-nav navbar-right">
	      <li>
	      	<% if current_user %>
	      	Welcome, <%= current_user.first_name %>!
	      	<%= link_to "Log out", session_path, method: :delete %>
	      	<% else %>
	      	<%= link_to "Sign up", new_user_path if !@is_signup %>
	      	<%= link_to "Log in", new_session_path if !@is_login %>
	      	<% end %>
	      </li>
	    </ul>
	  </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assetmap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/nav' %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/products/index.html.erb
<h1>Merch info</h1>

<img src="" alt="">

<h2>Product name</h2>
<h3>Make</h3>

<h4>Product Specs:</h4>
<p>Lorem ipsum dolor sit amet, maiores ornare ac fermentum, imperdiet ut vivamus a, nam lectus at nunc. Quam euismod sem, semper ut potenti pellentesque quisque. In eget sapien sed, sit duis vestibulum ultricies, placerat morbi amet vel, nullam in in lorem vel. In molestie elit dui dictum, praesent nascetur pulvinar sed, in dolor pede in aliquam, risus nec error quis pharetra. Eros metus quam augue suspendisse, metus rutrum risus erat in.  In ultrices quo ut lectus, etiam vestibulum urna a est, pretium luctus euismod n</p>

<a href="">Warranty Info</a>
<a href="">User Manual</a>

app/views/products/new.html.erb
<h1>Add New Merch</h1>

<%= form_for @product do |f| %>
	<%=f.text_field :product_name, placeholder: "Merch Name" %><br />
	<%=f.text_field :product_purchase_price, placeholder: "Purchase Price" %><br />
	<%=f.text_field :product_estimate_price, placeholder: "Estimate Price" %><br />
	<%=f.text_field :product_category_name, placeholder: "Merch Category Name" %><br />
	<%=f.text_field :product_make, placeholder: "Merch Make" %><br />
	<%=f.text_field :product_warranty, placeholder: "Does this Merch have a warranty" %><br />
	<%=f.text_field :product_warranty_length, placeholder: "If yes, how long?" %><br />

	<%= f.submit "Submit Merch" %>


	<% end %>

app/views/products/show.html.erb
<h1>Merch info</h1>

<img src="" alt="">

<h2>Product name</h2>
<h3>Make</h3>

<h4>Product Specs:</h4>
<p>Lorem ipsum dolor sit amet, maiores ornare ac fermentum, imperdiet ut vivamus a, nam lectus at nunc. Quam euismod sem, semper ut potenti pellentesque quisque. In eget sapien sed, sit duis vestibulum ultricies, placerat morbi amet vel, nullam in in lorem vel. In molestie elit dui dictum, praesent nascetur pulvinar sed, in dolor pede in aliquam, risus nec error quis pharetra. Eros metus quam augue suspendisse, metus rutrum risus erat in.  In ultrices quo ut lectus, etiam vestibulum urna a est, pretium luctus euismod n</p>

<a href="">Warranty Info</a>
<a href="">User Manual</a>

<%= link_to "Back to the list!", inventories_path %>

app/views/users/edit.html.erb
<h1>Edit User Profile</h1>

<%= form_for @user do |f| %>
	<%=f.text_field :first_name, placeholder: "First Name" %>
	<%=f.text_field :last_name, placeholder: "Last Name" %>
	<%=f.text_field :password, placeholder: "Password" %>
	<%=f.text_field :address, placeholder: "Address" %>
	<%=f.text_field :city, placeholder: "City" %>
	<%=f.text_field :state, placeholder: "State" %>
	<%=f.text_field :postal_code, placeholder: "Zip Code" %>
	<%=f.text_field :email_address, placeholder: "Address" %>

	<%= f.submit "Edit User!" %>


	<% end %>

app/views/users/index.html.erb
<h1>Asset Summary for <%= current_user.first_name %></h1>

<img src="" alt="">

<ul>
	<li><strong>Estimated Total Merch Worth <%= current_user.first_name %></strong></li>
	<li>Total Merch cost (price  paid):</li>
	<li>Estimated Most Valuable Merch:</li>
	<li>Most Expensive piece of Merch:</li>
	<li>Merch under warranty:</li>
	<li>Merch not under warranty:</li>
	<li>Soonest Merch warranty expiration:</li>
	<li>Merch warranty offers:</li>
</ul>

app/views/users/new.html.erb
<h1>Add new User</h1>

<%= form_for @user do |f| %>
	<%=f.text_field :first_name, placeholder: "First Name" %><br />
	<%=f.text_field :last_name, placeholder: "Last Name" %><br />
	<%=f.text_field :address, placeholder: "Address" %><br />
	<%=f.text_field :city, placeholder: "City" %><br />
	<%=f.text_field :state, placeholder: "State" %><br />
	<%=f.text_field :postal_code, placeholder: "Postal Code" %><br />
	<%=f.text_field :email_address, placeholder: "Email" %><br />

	<%= f.password_field :password, placeholder: "password ..." %><br />
	<%= f.password_field :password_confirmation, placeholder: "... and again" %>

	<%= f.submit "Sign up!" %>


	<% end %>

app/views/users/reactivate.html.erb
<h1>Add new User</h1>

<%= form_for @user do |f| %>
	<%=f.check_box :is_active %><br />

	<%= f.submit "Reactivate me!" %>

	<% end %>